package org.unicefkidpower.schools.powerband.command;

/**
 * Copyright 2015 ~ 2019 UNICEF CalorieCloud org
 * Created by Dayong Li on 9/29/2015.
 */

public class CmdAniCelebDisplay extends BandCommand {
	public static final String TAG = "CmdAniCelebDisplay";

	public CmdAniCelebDisplay() {
		_code = COMMAND_SEND_CELEBRATION;
	}

	@Override
	public byte[] getBytes(int block) {
		byte[] command = new byte[16];
		int checksum = 0;

		command[0] = _code;
		for (int i = 1; i < 15; ++i) {
			command[i] = 0;
		}

		for (int i = 0; i < 15; ++i) {
			checksum += command[i];
		}

		command[15] = (byte) (checksum & 255);
		return command;
	}

	static public class CmdAniCelebDisplayParser extends BandCommandResponseParser {

		public static CmdAniCelebDisplayParser _instance;

		private CmdAniCelebDisplayParser() {
			success_code = BandCommandResponse.CODE_SEND_ANIMATEDCELEBRATE_SUCCESS;
			failure_code = BandCommandResponse.CODE_SEND_ANIMATEDCELEBRATE_FAILURE;
		}

		public static CmdAniCelebDisplayParser sharedInstance() {
			if (_instance == null)
				_instance = new CmdAniCelebDisplayParser();
			return _instance;
		}

		@Override
		public int parse(byte code, byte[] response) {
			_response = new CmdAniCelebDisplaySendRes();

			int ret = super.parse(code, response);
			if (ret != PARSE_FINISHED)
				return ret;

			if (code == success_code) {
				_response._success = true;
			} else {
				_response._success = false;
			}
			return PARSE_FINISHED;
		}
	}

	/**
	 * Command Response Class : generated by Command Parser Class
	 */
	static public class CmdAniCelebDisplaySendRes extends BandCommandResponse {
		@Override
		public byte getCommandCode() {
			return CODE_SEND_ANIMATEDCELEBRATE_SUCCESS;
		}
	}

}
