package org.unicefkidpower.schools.powerband.command;

import org.unicefkidpower.schools.model.DailyActivityData.SummaryData;

/**
 * Copyright 2015 ~ 2019 UNICEF CalorieCloud org
 * Created by donal_000 on 2/3/2015.
 * Modified by dyl on 12/10/2015
 */
public class CmdDailySummaryGet extends BandCommand {
	protected int _days;

	public CmdDailySummaryGet(int days) {
		_code = CODE_GET_DAILYSUMMARYDATA;
		_days = days;
	}

	@Override
	public byte[] getBytes(int no_block) {
		byte[] command = new byte[16];

		// get daily total activity data -----------------------------
		command[0] = _code;
		command[1] = (byte) _days;
		for (int i = 2; i < 15; i++)
			command[i] = 0;

		int checksum = 0;
		for (int i = 0; i < 15; i++) {
			checksum += command[i];
		}
		command[15] = (byte) (checksum & 255);
		return command;
	}

	static public class CmdDailySummaryGetParser extends BandCommandResponseParser {
		private static CmdDailySummaryGetParser _instance;

		private int mBeforeDay;
		private int mSteps;
		private int mCalories;
		private int mDistance;
		private int mActivityTime;
		private int mLowActivityTime;
		private int mHighActiveTime;

		private CmdDailySummaryGetParser() {
			success_code = BandCommandResponse.CODE_GET_DAILYSUMMARYDATA_SUCCESS;
			failure_code = BandCommandResponse.CODE_GET_DAILYSUMMARYDATA_FAILED;
		}

		public static CmdDailySummaryGetParser sharedInstance() {
			if (_instance == null)
				_instance = new CmdDailySummaryGetParser();
			return _instance;
		}

		@Override
		public int parse(byte code, byte[] response) {
			_response = new CmdDailySummaryGetRes();

			int ret = super.parse(code, response);
			if (ret != PARSE_FINISHED)
				return ret;

			int index = 0xFF & response[1];
			if (code == success_code) {
				if (index == 0) {
					mBeforeDay = 0xFF & response[2];
					mSteps = 256 * 256 * (255 & response[6])
							+ 256 * (255 & response[7])
							+ (255 & response[8]);
					mCalories = 256 * 256 * (255 & response[12]) +
							256 * (255 & response[13]) + (255 & response[14]);

					_response._success = true;
					return PARSE_WAITING;
				} else if (index == 1) {
					mDistance = 256 * 256 * (255 & response[6]) +
							256 * (255 & response[7]) + (255 & response[8]);
					mActivityTime = 256 * (255 & response[9]) + (255 & response[10]);
					mLowActivityTime = 256 * (255 & response[11]) + (255 & response[12]);
					mHighActiveTime = 256 * (255 & response[13]) + (255 & response[14]);

					SummaryData mDailySummaryData = new SummaryData();
					mDailySummaryData.steps = mSteps;
					mDailySummaryData.calories = mCalories / 100.0;
					mDailySummaryData.distance = mDistance / 10.0; //0.1km
					mDailySummaryData.duration = mActivityTime;

					mDailySummaryData.mvpa = mLowActivityTime;
					mDailySummaryData.vpa = mHighActiveTime;

					((CmdDailySummaryGetRes) _response).setBeforeDay(mBeforeDay);
					((CmdDailySummaryGetRes) _response).setDailySummaryData(mDailySummaryData);
					_response._success = true;
					return PARSE_FINISHED;
				} else {
					_response._success = false;
					return PARSE_ERROR;
				}
			} else {
				_response._success = false;
			}
			return PARSE_FINISHED;
		}

	}

	/**
	 * Command Response Class : generated by Command Parser Class
	 */
	static public class CmdDailySummaryGetRes extends BandCommandResponse {
		protected int beforeDay;
		protected SummaryData _data;

		public SummaryData getDailySummaryData() {
			return _data;
		}

		public void setDailySummaryData(SummaryData data) {
			_data = data;
		}

		public void setBeforeDay(int day) {
			beforeDay = day;
		}

		public int getBeforeDay() {
			return beforeDay;
		}

		@Override
		public byte getCommandCode() {
			return CODE_GET_DAILYSUMMARYDATA_SUCCESS;
		}
	}

}
