package org.unicefkidpower.schools.powerband.command;

import org.unicefkidpower.schools.helper.OSDate;
import org.unicefkidpower.schools.model.DailyActivityData.DetailData;

import java.util.ArrayList;
import java.util.Date;

/**
 * Copyright 2015 ~ 2019 UNICEF CalorieCloud org
 * Created by donal_000 on 3/6/2015.
 * Modified by dyl on 12/10/2015
 */
public class CmdDailyDetailedGet extends BandCommand {
	protected int _days;

	public CmdDailyDetailedGet(int days) {
		_code = CODE_GET_DAILYDATA;
		_days = days;
	}

	@Override
	public byte[] getBytes(int no_block) {
		byte[] command = new byte[16];

		// get daily total activity data -----------------------------
		command[0] = _code;
		command[1] = (byte) _days;
		for (int i = 2; i < 15; i++)
			command[i] = 0;

		int checksum = 0;
		for (int i = 0; i < 15; i++) {
			checksum += command[i];
		}
		command[15] = (byte) (checksum & 255);
		return command;
	}

	static public class CmdDailyDetailedGetParser extends BandCommandResponseParser {
		private static CmdDailyDetailedGetParser _instance;

		int year;
		int month;
		int day;
		ArrayList<DetailData> data;

		private CmdDailyDetailedGetParser() {
			success_code = BandCommandResponse.CODE_GET_DAILYDATA_SUCCESS;
			failure_code = BandCommandResponse.CODE_GET_DAILYDATA_FAILED;
		}

		public static CmdDailyDetailedGetParser sharedInstance() {
			if (_instance == null)
				_instance = new CmdDailyDetailedGetParser();
			return _instance;
		}

		@Override
		public int parse(byte code, byte[] response) {
			_response = new CmdDailyDetailedRes();

			int ret = super.parse(code, response);
			if (ret != PARSE_FINISHED)
				return ret;

			if (code == success_code) {
				int index = (0xFF & response[5]);
				if (index == 0) {
					data = new ArrayList<>();

					year = Integer.valueOf(String.format("%x", 0xFF & response[2])) + 2000;
					month = Integer.valueOf(String.format("%x", 0xFF & response[3])) - 1;
					day = Integer.valueOf(String.format("%x", 0xFF & response[4]));

					if (year <= 2000) year = 0;
					if (month < 0) month = 0;
					if (day < 0) day = 0;
				}

				int totalmin = 15 + 15 * index;
				int hour = totalmin / 60;
				int min = totalmin % 60;

				if (((0xFF & response[1]) == 0xF0)) {
					// activity data
					if ((0xFF & response[6]) == 0) {
						int calories = (0x100 * (0xFF & response[8])) + (0xFF & response[7]);
						int steps = (0x100 * (0xFF & response[10])) + (0xFF & response[9]);
						int distance = (0x100 * (0xFF & response[12])) + (0xFF & response[11]);
						int run_steps = (0x100 * (0xFF & response[14])) + (0xFF & response[13]);

						// filter log
						if (steps != 0 && calories != 0 && distance != 0) {
							DetailData dailyData = new DetailData();
							String time = String.format("%02d%02d", hour, min);
							dailyData.time = time;
							dailyData.steps = steps;
							dailyData.calories = calories / 100.0d;
							dailyData.distance = distance / 100.0d; // distance unit is in 0.01KM
							//dailyData.run_steps = run_steps;

							data.add(dailyData);
						}
					} else {
						// sleep data
					}

					// time scale index == 95 (the last data for daily data)
					if (index == 95) {
						_response._success = true;

						((CmdDailyDetailedRes) _response).year = year;
						((CmdDailyDetailedRes) _response).month = month;
						((CmdDailyDetailedRes) _response).day = day;
						((CmdDailyDetailedRes) _response).setDailyData(data);
						return PARSE_FINISHED;
					} else {
						_response._success = true;
						return PARSE_WAITING;
					}
				} else if ((0xFF & response[1]) == 0xFF) {
					// there are no data
					DetailData dailyData = new DetailData();
					dailyData.steps = 0;
					dailyData.calories = 0;
					dailyData.distance = 0;
					dailyData.time = String.format("%02d%02d", 0, 0);

					data.add(dailyData);

					_response._success = true;
					((CmdDailyDetailedRes) _response).year = year;
					((CmdDailyDetailedRes) _response).month = month;
					((CmdDailyDetailedRes) _response).day = day;
					((CmdDailyDetailedRes) _response).setDailyData(data);
					return PARSE_FINISHED;
				} else {
					_response._success = false;
					return PARSE_ERROR;
				}
			} else {
				_response._success = false;
				return PARSE_FINISHED;
			}
		}
	}

	/**
	 * Command Response Class : generated by Command Parser Class
	 */
	static public class CmdDailyDetailedRes extends BandCommandResponse {
		protected int beforeDay;

		public int year;
		public int month;
		public int day;
		protected ArrayList<DetailData> _data;

		public ArrayList<DetailData> getDailyData() {
			return _data;
		}

		public void setDailyData(ArrayList<DetailData> data) {
			_data = data;
		}

		public void setBeforeDay(int beforeDay, Date now) {
			this.beforeDay = beforeDay;

			if (year <= 0 && month <= 0 && day <= 0) {
				OSDate dt = new OSDate(now).offsetDay(-1 * beforeDay);

				this.year = dt.Year();
				this.month = dt.Month();
				this.day = dt.DayOfMonth();
			}
		}

		public int getBeforeDay() {
			return beforeDay;
		}

		@Override
		public byte getCommandCode() {
			return CODE_GET_DAILYDATA_SUCCESS;
		}
	}

}
