package org.unicefkidpower.schools.powerband.command;

import org.unicefkidpower.schools.helper.OSDate;

import java.util.Date;

/**
 * Copyright 2015 ~ 2019 UNICEF CalorieCloud org
 * Created by donal_000 on 2/4/2015.
 * Modified by dyl on 12/10/2015
 */
public class CmdDeviceTimeSet extends BandCommand {
	protected Date _date;

	public CmdDeviceTimeSet(Date dt) {
		_date = dt;
		_code = CODE_SET_DEVICETIME;
	}

	public static int convert(int n) {
		return Integer.valueOf(String.valueOf(n), 16);
	}

	@Override
	public byte[] getBytes(int no_block) {

		String deviceTimeString = new OSDate(_date).toStringWithFormat("yyyy-MM-dd HH:mm:ss");
		String[] dateSplitObj = deviceTimeString.split(" ");
		String[] dateStringObj = dateSplitObj[0].split("-");
		String[] timeStringObj = dateSplitObj[1].split(":");
		int year = Integer.parseInt(dateStringObj[0]) - 2000;
		int month = Integer.parseInt(dateStringObj[1]);
		int day = Integer.parseInt(dateStringObj[2]);
		int hh = Integer.parseInt(timeStringObj[0]);
		int mm = Integer.parseInt(timeStringObj[1]);
		int ss = Integer.parseInt(timeStringObj[2]);


		byte[] var1 = new byte[16];
		byte var2 = 0;
		var1[0] = _code;
		var1[1] = (byte) convert(year);
		var1[2] = (byte) convert(month);
		var1[3] = (byte) convert(day);
		var1[4] = (byte) convert(hh);
		var1[5] = (byte) convert(mm);
		var1[6] = (byte) convert(ss);
		for (int i = 7; i < 15; ++i) {
			var1[i] = 0;
		}
		for (int i = 0; i < 15; ++i) {
			var2 += var1[i];
		}
		var1[15] = (byte) (var2 & 255);

		return var1;
	}

	static public class CmdDeviceTimeSetParser extends BandCommandResponseParser {
		private static CmdDeviceTimeSetParser _instance;

		private CmdDeviceTimeSetParser() {
			success_code = BandCommandResponse.CODE_SET_DEVICETIME_SUCCESS;
			failure_code = BandCommandResponse.CODE_SET_DEVICETIME_FAILED;
		}

		public static CmdDeviceTimeSetParser sharedInstance() {
			if (_instance == null)
				_instance = new CmdDeviceTimeSetParser();
			return _instance;
		}

		@Override
		public int parse(byte code, byte[] response) {
			_response = new CmdDeviceTimeSetRes();

			int ret = super.parse(code, response);
			if (ret != PARSE_FINISHED)
				return ret;

			if (code == success_code) {
				_response._success = true;
			} else {
				_response._success = false;
			}
			return PARSE_FINISHED;
		}
	}

	/**
	 * Command Response Class : generated by Command Parser Class
	 */
	static public class CmdDeviceTimeSetRes extends BandCommandResponse {
		@Override
		public byte getCommandCode() {
			return CODE_SET_DEVICETIME_SUCCESS;
		}
	}

}
