package org.unicefkidpower.schools.powerband.command;

import org.unicefkidpower.schools.helper.Logger;

/**
 * Copyright 2015 ~ 2019 UNICEF CalorieCloud org
 * Created by donal_000 on 2/13/2015.
 * Modified by dyl on 12/10/2015
 */
public class CmdMessageSet extends BandCommand {
	public static final String TAG = "CmdMessageSet";

	protected int _slot;
	protected String _message;

	public CmdMessageSet(int slot, String message) {
		_code = BandCommand.CODE_SET_MESSAGE;
		_slot = slot;
		_message = message;
	}

	@Override
	public byte[] getBytes(int no_block) {
		if (_message == null) {
			Logger.log(TAG, "setMessage, message is null, return");
			return null;
		}

		if (_message.length() > 11) {
			Logger.log(TAG, "setMessage(%d, %s), message.length(%d) > 11, return null", _slot, _message, _message.length());
			return null;
		}

		if (_slot < 0 || _slot > 3) {
			Logger.log(TAG, "setMessage(%d, %s), not index in 0 ~ 31, return null", _slot, _message);
			return null;
		}

		byte[] command = new byte[16];
		int checksum = 0;
		command[0] = _code;
		command[1] = (byte) _slot;
		for (int i = 2; i < 15; ++i) {
			command[i] = 0;
		}

		byte[] bytesForName = _message.getBytes();
		for (int i = 0; i < _message.length(); i++) {
			command[i + 2] = bytesForName[i];
		}

		for (int i = 0; i < 15; ++i) {
			checksum += command[i];
		}

		command[15] = (byte) (checksum & 255);
		return command;
	}

	static public class CmdMessageSetParser extends BandCommandResponseParser {
		public static CmdMessageSetParser _instance;

		private CmdMessageSetParser() {
			success_code = BandCommandResponse.CODE_SET_MESSAGE_SUCCESS;
			failure_code = BandCommandResponse.CODE_SET_MESSAGE_FAILED;
		}

		public static CmdMessageSetParser sharedInstance() {
			if (_instance == null)
				_instance = new CmdMessageSetParser();
			return _instance;
		}

		@Override
		public int parse(byte code, byte[] response) {
			_response = new CmdMessageSetRes();

			int ret = super.parse(code, response);
			if (ret != PARSE_FINISHED)
				return ret;

			if (code == success_code) {
				_response._success = true;
			} else {
				_response._success = false;
			}
			return PARSE_FINISHED;
		}
	}

	/**
	 * Command Response Class : generated by Command Parser Class
	 */
	static public class CmdMessageSetRes extends BandCommandResponse {
		@Override
		public byte getCommandCode() {
			return CODE_SET_MESSAGE_SUCCESS;
		}
	}

}
