package org.unicefkidpower.schools.powerband.command;

/**
 * Copyright 2015 ~ 2019 UNICEF CalorieCloud org
 * Created by donal_000 on 2/13/2015.
 * Modified by dyl on 12/10/2015
 */
public class CmdPersonalInfoSet extends BandCommand {
	public static final String TAG = "CmdPersonalInfoSet";

	protected int _gender;
	protected int _age;
	protected int _height;
	protected int _weight;
	protected int _strideLength;

	/**
	 * @param gender       - 0 : female, 1 : male
	 * @param age
	 * @param height
	 * @param weight
	 * @param strideLength
	 */
	public CmdPersonalInfoSet(int gender, int age, int height, int weight, int strideLength) {
		_code = CODE_SET_PERSONALINFORMATION;

		_gender = gender;
		_age = age;
		_height = height;
		_weight = weight;
		_strideLength = strideLength;
	}

	@Override
	public byte[] getBytes(int no_block) {
		byte[] command = new byte[16];
		int checksum = 0;
		command[0] = _code;
		for (int i = 1; i < 15; ++i) {
			command[i] = 0;
		}

		command[1] = (byte) _gender;
		command[2] = (byte) _age;
		command[3] = (byte) _height;
		command[4] = (byte) _weight;
		command[5] = (byte) _strideLength;

		for (int i = 0; i < 15; ++i) {
			checksum += command[i];
		}
		command[15] = (byte) (checksum & 255);

		//
		return command;
	}

	static public class CmdPersonalInfoSetParser extends BandCommandResponseParser {
		public static CmdPersonalInfoSetParser _instance;

		private CmdPersonalInfoSetParser() {
			success_code = BandCommandResponse.CODE_SET_PERSONALINFORMATION_SUCCESS;
			failure_code = BandCommandResponse.CODE_SET_PERSONALINFORMATION_FAILED;
		}

		public static CmdPersonalInfoSetParser sharedInstance() {
			if (_instance == null)
				_instance = new CmdPersonalInfoSetParser();
			return _instance;
		}

		@Override
		public int parse(byte code, byte[] response) {
			_response = new CmdPersonalInfoSetRes();

			int ret = super.parse(code, response);
			if (ret != PARSE_FINISHED)
				return ret;

			if (code == success_code) {
				_response._success = true;
			} else {
				_response._success = false;
			}
			return PARSE_FINISHED;
		}
	}

	/**
	 * Command Response Class : generated by Command Parser Class
	 */
	static public class CmdPersonalInfoSetRes extends BandCommandResponse {
		@Override
		public byte getCommandCode() {
			return CODE_SET_PERSONALINFORMATION_SUCCESS;
		}
	}


}
