package org.unicefkidpower.schools.powerband.command;

/**
 * Copyright 2015 ~ 2019 UNICEF CalorieCloud org
 * Created by donal_000 on 2/3/2015.
 * Modified by dyl on 12/10/2015
 */
public class CmdStorageInfoGet extends BandCommand {
	public static final String TAG = "CmdStorageInfoGet";

	public CmdStorageInfoGet() {
		_code = BandCommand.CODE_GET_STORAGEINFORMATION;
	}

	@Override
	public byte[] getBytes(int no_block) {
		byte[] command = new byte[16];
		int checksum = 0;
		command[0] = _code;
		for (int i = 1; i < 15; ++i) {
			command[i] = 0;
		}

		for (int i = 0; i < 15; ++i) {
			checksum += command[i];
		}

		command[15] = (byte) (checksum & 0xFF);

		return command;
	}

	public static CmdStorageInfoGetRes getEmptyResponse() {
		CmdStorageInfoGetRes res = new CmdStorageInfoGetRes();
		res._success = true;
		res._storageInformation = 0x7FFFFFFF;
		return res;
	}

	static public class CmdStorageInfoGetParser extends BandCommandResponseParser {
		private static CmdStorageInfoGetParser _instance;

		private CmdStorageInfoGetParser() {
			success_code = BandCommandResponse.CODE_GET_STORAGEINFORMATION_SUCCESS;
			failure_code = BandCommandResponse.CODE_GET_STORAGEINFORMATION_FAILURE;
		}

		public static CmdStorageInfoGetParser sharedInstance() {
			if (_instance == null)
				_instance = new CmdStorageInfoGetParser();
			return _instance;
		}

		@Override
		public int parse(byte code, byte[] response) {
			_response = new CmdStorageInfoGetRes();

			int ret = super.parse(code, response);
			if (ret != PARSE_FINISHED)
				return ret;

			if (code == success_code) {
				long byte1 = ((response[1] & 0xFF) << 24);
				long byte2 = ((response[2] & 0xFF) << 16);
				long byte3 = ((response[3] & 0xFF) << 8);
				long byte4 = (response[4] & 0xFF);
				long storagebytes = byte1 + byte2 + byte3 + byte4;

				((CmdStorageInfoGetRes) _response).setStorageInformation(storagebytes);
				_response._success = true;
			} else {
				((CmdStorageInfoGetRes) _response).setStorageInformation(0);
				_response._success = false;
			}
			return PARSE_FINISHED;
		}
	}

	/**
	 * Command Response Class : generated by Command Parser Class
	 */
	static public class CmdStorageInfoGetRes extends BandCommandResponse {
		protected long _storageInformation;

		public CmdStorageInfoGetRes() {
			_storageInformation = 0;
		}

		public long getStorageInformation() {
			return _storageInformation;
		}

		public void setStorageInformation(long storageInformation) {
			_storageInformation = storageInformation;
		}

		@Override
		public byte getCommandCode() {
			return CODE_GET_STORAGEINFORMATION_SUCCESS;
		}
	}

}
